# Generated by Django 3.2.9 on 2021-11-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_date_added_cart_date_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
